// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1, arg2) {
  return window['go']['main']['App']['Authenticate'](arg1, arg2);
}

export function BoostClub() {
  return window['go']['main']['App']['BoostClub']();
}

export function ClaimReward() {
  return window['go']['main']['App']['ClaimReward']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function SyncCards() {
  return window['go']['main']['App']['SyncCards']();
}
